#!/bin/sh
## not executable, just for syntax highlighting

banner() ### ( name )
{
	local variant="${1-}"
	[ "$variant" ] || variant="$(distinfo ID)"
	local banner="$dir/RES/BANNERS/$variant"
	[ -f "$banner" ] || \
	{
		[ "${BANNER_FALLBACK-}" = 1 ] || return 1
		banner="$dir/RES/BANNERS/DEFAULT"
	}
	local singleline=0
	[ "$COLUMNS" -ge "$(head -1 "$banner")" ] || singleline=1
	if [ "$singleline" = 1 ]
	then tail +2 "$banner" | head -1 ; repeat "$COLUMNS" '─'
	else tail +3 "$banner"
	fi
}

todo()
{
	echo "╔═════╗"
	echo -n "║Todo:╟"
	repeat "$(($COLUMNS - 7))" '─'; echo
	echo "╚═════╝"
	cat ~/TODO
	[ ! -f ~/TODO_EXT ] || cat ~/TODO_EXT
	repeat "$COLUMNS" '─'; echo
}

greet()
{
	#[ "$in_termux" = 0 ] || rm -f "$PREFIX/etc/motd"
	hitokoto
	BANNER_FALLBACK=1 banner
	echo -n "PID: "; getshpid
	todo
	cat "$dir/PS"
	[ ! -f ~/PS_EXT ] || cat ~/PS_EXT
}
