#!/bin/bash
## not executable, just for syntax highlighting

banner() ### ( name )
{
	local variant=${1-}
	[ "$variant" ] || variant=$(distinfo ID)
	local banner=$s_dir/RES/BANNERS/$variant
	[ -f "$banner" ] || {
		[ "${BANNER_FALLBACK-}" = 1 ] || return 1
		banner=$s_dir/RES/BANNERS/DEFAULT
	}
	local singleline=0
	[ "$in_fbcon" = 0 ] || singleline=1
	[ "$COLUMNS" -ge "$(head -1 "$banner")" ] || singleline=1
	if [ "$singleline" = 1 ]
	then tail +2 "$banner" | head -1 ; repeat "$COLUMNS" '─'; echo
	else tail +3 "$banner"
	fi
}

todo()
{
	echo "╔═════╗"
	echo -n "║Todo:╟"
	repeat "$(( COLUMNS - 7 ))" '─'; echo
	echo "╚═════╝"
	cat ~/TODO
	[ ! -f ~/TODO_EXT ] || cat ~/TODO_EXT
	repeat "$COLUMNS" '─'; echo
}

greet()
{
	[ "$in_fbcon" = 0 ] || setfont
	#[ "$in_termux" = 0 ] || rm -f "$PREFIX/etc/motd"
	BANNER_FALLBACK=1 banner
	[ "$in_fbcon" = 0 ] && [ -f "$s_dir/TMP/hitokoto" ] && cat "$s_dir/TMP/hitokoto" && \
	  echo || echo 'Be yourself.'
	quietly require linux && echo -n "PID:" && getshpid || :
	todo
	cat "$s_dir/PS"
	[ ! -f ~/PS_EXT ] || cat ~/PS_EXT
	[ "$in_fbcon" = 1 ] || hitokoto "$s_dir/TMP/hitokoto" 30 30 &
}
