#!/bin/sh
## not executable, just for syntax highlighting

### head_except <-c|-v> <n> <file>
head_except(){ head "$1" "$(("$(wc -l < "$3")" - "$2"))" "$3";}

debugsh()
{
	local tty="/dev/tty" shell="${1-bash}"; [ "$#" = 0 ] || shift 1
	echo "For convenience of debugging, only retval 114 will raise an error." >/dev/tty
	PS1="debug> " "$shell" "$@" <"$tty" >"$tty" 2>"$tty" || \
	  [ "$?" != 114 ] || return 1
}

justdo()
{
	local i
	for i in "$@"
	do eval "$i" >/dev/null 2>&1 || :
	done
}

countdown() ### ( time/s: 5, [msg], [finmsg] )
{
	local i="$1" msg="${2-}" finmsg="${3-}"
	while [ "$i" -gt 0 ]
	do	echo "$msg$i"
		sleep 1
		i="$(($i - 1))"
	done
	[ "$finmsg" = "" ] || echo "$finmsg"
}
