#!/bin/bash
## not executable, just for syntax highlighting

rsync_size()
{
require cmd:rsync
	rsync -a --no-motd -r --list-only "$1" | calculate_sum 2
}

hitokoto() ## (out_file:stdout conn_timeout:0.6 maxtime: 0.6)
{
require cmd:curl
	local outfile="${1-/dev/stdout}" timeout="${2-0.6}" maxtime="${3-0.6}"
	local outdir="${outfile%/*}"
	[ -d "$outdir" ] || mkdir -p "$outdir"
	curl -s -o "$outfile" --connect-timeout "$timeout" --max-time "$maxtime" \
	  https://v1.hitokoto.cn?encode=text || return 1
}

dynv6_update()
{
	local tokenfile="$1" zone interval token comment
	echo 'Reading token file...'
	IFS=' ' read -r < "$tokenfile" zone interval token comment
	echo 'Update interval is '"$interval"' seconds.'
	local i=1
	echo 'Entering loop...'
	while true
	do	echo 'In loop '"$counter"'.'
		echo "$counter"': Fetching IP address...'
		local ipv4="$(curl -s --connect-timeout 3 -m 3 ifconfig.me)"
		local ipv6=6to4
		local ipv6prefix=6to4
		echo "$counter"': Sending request...'
		curl -s --connect-timeout 3 -m 3 'https://dynv6.com/api/update?zone='"$zone"'&token='"$token"'&ipv4='"$ipv4"'&ipv6='"$ipv6"'&ipv6prefix='"$ipv6prefix" || true
		echo '\n'"$counter"': Sleeping...'
		sleep "$interval"
		: $(( a += 1 ))
	done
}
