#!/bin/bash
## not executable, just for syntax highlighting

apksize()
{
require cmd:apk
	apk list -I --manifest | awk '{print $1}' | \
	  xargs -J {} apk info -s --verbose "{}" | awk '{print $2 $3 " " $1}' | \
	  sed 's/\:$//' | sort -h
}

apk_world_dedup()
{
require cmd:apk
	local i
	clear
	echo 'Enter password to start deduplication'
	echo 'Current WORLD:'
	cat /etc/apk/world | xargs
	for i in $(cat /etc/apk/world)
	do echo n | doas apk --interactive del "$i" || true
	clear
	echo 'Deduplicating...'
	echo 'Current WORLD:'
	cat /etc/apk/world | xargs
	done
	echo 'Deduplication finished'
}

pacman_minimize_explicit()
{
require cmd:pacman
	LANG=C pacman -Qei |
	  grep -E '^Name|^Required By' |
	  awk '{ if(NR%2) {line=$3} else { if ($4!="None") {print line} } }' |
	  xargs -or elevate pacman -D --asdeps
}

parse_apt_rdepends()
{
	local dep=0 line pkg
	while IFS= read -r line
		do case "$line" in
		'  '*|' |'*) dep=1;;
		'Reverse Depends:');;
		*)	[ "$dep" == 0 ] || echo "$pkg"
			pkg="$line"; dep=0;;
		esac
	done
	[ "$dep" == 0 ] || echo "$pkg"
}

apt_minimize_manual()
{
require cmd:apt-mark cmd:apt-cache
	local pkgs="$(apt-cache rdepends -i --installed $(apt-mark showmanual) | parse_apt_rdepends)"
	[ "$pkgs" ] || return 0
	elevate apt-mark auto "$pkgs"
}
