#!/bin/sh
## not executable, just for syntax highlighting

apksize()
{
require cmd:apk
	apk list -I --manifest | awk '{print $1}' | \
	  xargs -J {} apk info -s --verbose "{}" | awk '{print $2 $3 " " $1}' | \
	  sed 's/\:$//' | sort -h
}

apk_world_dedup()
{
require cmd:apk
	local i
	clear
	echo 'Enter password to start deduplication'
	echo 'Current WORLD:'
	cat /etc/apk/world | xargs
	for i in $(cat /etc/apk/world)
	do echo n | doas apk --interactive del "$i" || true
	clear
	echo 'Deduplicating...'
	echo 'Current WORLD:'
	cat /etc/apk/world | xargs
	done
	echo 'Deduplication finished'
}
