#!/bin/bash
## not executable, just for syntax highlighting

apksize()
{
require cmd:apk
	apk list -I --manifest | awk '{print $1}' | \
	  xargs -J {} apk info -s --verbose "{}" | awk '{print $2 $3 " " $1}' | \
	  sed 's/\:$//' | sort -h
}

apk_world_dedup()
{
require cmd:apk
	local i
	clear
	echo 'Enter password to start deduplication'
	echo 'Current WORLD:'
	cat /etc/apk/world | xargs
	for i in $(< /etc/apk/world)
	do echo n | doas apk --interactive del "$i" || true
	clear
	echo 'Deduplicating...'
	echo 'Current WORLD:'
	cat /etc/apk/world | xargs
	done
	echo 'Deduplication finished'
}

pacman_minimize_explicit()
{
require cmd:pacman
	local pkgs
	pkgs=$(LANG=C pacman -Qei | grep -E '^Name|^Required By' |
	  awk '{if (NR%2) {line=$3} else {if ($4!="None") {print line}}}')
	[ "$pkgs" ] || return 0
	echo "marking as dep: $pkgs"
	elevate pacman -D --asdeps $pkgs
}

parse_apt_rdepends()
{
	local dep=0 line pkg
	while IFS= read -r line
		do case "$line" in
		'  '*|' |'*) dep=1;;
		'Reverse Depends:');;
		*)	[ "$dep" == 0 ] || echo "$pkg"
			pkg="$line"; dep=0;;
		esac
	done
	[ "$dep" == 0 ] || echo "$pkg"
}

apt_minimize_manual()
{
require cmd:apt-mark cmd:apt-cache
	local pkgs
	pkgs=$(apt-cache rdepends -i --installed $(apt-mark showmanual) | parse_apt_rdepends)
	[ "$pkgs" ] || return 0
	echo "marking as auto: $pkgs"
	elevate apt-mark auto $pkgs
}


arch_rate_mirrors()
{
require cmd:rate-mirrors
	local i target=${1-/etc/pacman.d/mirror.d}
	elevate mkdir -p "$target"
	for i in arch archlinuxcn cachyos #chaotic-aur
	do rate-mirrors "$i" | elevate tee "$target/$i"
	done

	for i in v3 #_v4
	do sed -e "s/\$arch/x86_64_$i/g" "$target/cachyos" | elevate tee "$target/cachyos_$i" > /dev/null
	done
}

pacsize()
{
	LANG=C pacman -Qi | \
	  grep -E '^Name|^Installed Size|^Install Reason' | \
	  sed -e 's/^Install Reason  : Installed as a dependency for another package$/dep/g' \
	    -e 's/^Install Reason  : Explicitly installed$/exp/g' | \
	  xargs -L 3 | awk '{print $7$8" "$9" "$3"'"$CsReset"'"}' | \
	  sort -h | \
	  sed -e 's/exp /'"$cfBlue"'/g' -e 's/dep //g'
}
