#!/bin/sh ## not executable, just for syntax highlighting

[ "${_Y_initialized-}" = 1 ] && error "Y already initialized" || : 
## start of main

. "$(dirname "$(dirname "$(realpath "$0")")")/S/COMMON"

require cmd:yadm 

config_default="dotfiles"

allconfigs()
{
	ls -1 "$dir/CONFIG/"
}
useconfig()
{
	config="$1"
	[ "$config" ] || config="$config_default"
	pathlist="$dir/CONFIG/$config/PATH"
	excludelist="$dir/CONFIG/$config/EXCLUDE"
	yadmconfig="$dir/CONFIG/$config/yadm/"
	yadmdata="$dir/DATA/$config/"
	repodir="$dir/DATA/$config/repo.git/"
	worktree="$(_yadm gitconfig get core.worktree)"
}
_yadm() ## hooked yadm
{
	[ -d "$yadmdata" ] || error "config not enabled"
	yadm -Y "$yadmconfig" --yadm-data "$yadmdata" "$@"
}

if [ "${noautoload-}" = 1 ]
then :
else	if [ "$#" = 0 ]
	then error "please specify config or use '' to use default: $config_default"
	else useconfig "${1-}"; shift
	fi
fi

## end of main
_Y_initialized=1
