#!/bin/sh -eu

. "$(dirname "$0")/COMMON"

yadm rm -rqf --cached "$worktree"
yadm -C "$worktree" add --pathspec-from-file="$pathlist"
yadm -C "$worktree" rm -rq --cached --pathspec-from-file="$excludelist"
set +u
if [ "$1" ]
then yadm commit -qm "$1"
else yadm commit -qm update
fi
set -u
yadm show --stat
