#!/bin/sh -eu

. "$(dirname "$(realpath "$0")")/COMMON"

termux_gen_world()
{
	[ "$in_termux" = 1 ] || return 0
	apt-mark showmanual > "$HOME/.termux/world"
}

flatpak_gen_world()
{
	require cmd:flatpak || return 0
	LANG=C flatpak list --app --columns=name | tail +2 > "$dir/FLATPAK_WORLD"
}

add_files()
{
	_yadm rm -rqf --ignore-unmatch --cached "$worktree"
	_yadm -C "$worktree" add --pathspec-from-file="$pathlist"
	is_empty "$excludelist" || _yadm -C "$worktree" rm -rqf --ignore-unmatch --cached --pathspec-from-file="$excludelist"
}

confirmation()
{
	_yadm --no-pager diff --cached --stat
	while true
	do echo "Continue?"
	echo "y:commit n:discard v:verbose"
	read -r input
	case "$input" in
	y|Y) return 0;;
	n|N) error "operation cancelled";;
	v|V)	_yadm --no-pager diff --cached
		while true
		do echo "Confirm?"
		echo "y:commit n:discard"
		read -r input
		case "$input" in
		y|Y) return 0;;
		n|N) error "operation cancelled";;
		esac
		done;;
	esac
	done
}

do_commit()
{
	_yadm commit -qm "$1"
}

show_result()
{
	_yadm --no-pager show --stat
}

ask_push()
{
	while true
	do echo "Push now?"
	echo "y:push f:push(force) n:skip"
	read -r input
	case "$input" in
	y|Y) _yadm push; pushed=1; return 0;;
	f|F) _yadm push -f; pushed=1; return 0;;
	n|N) return 0;;
	esac
	done
}

termux_gen_world
flatpak_gen_world
add_files
confirmation

if [ "$#" -gt 0 ]
then do_commit "$1"
else do_commit "update"
fi

show_result
ask_push || error "Push failed, try to manually push"
[ "$pushed" = 1 ] || ( echo "Don't forget to push" )
