#!/bin/sh -eu

. "$(dirname "$(realpath "$0")")/COMMON"

echo -n "sorting..."
export LC_ALL=C
tr -s '\n' < "$pathlist" | sort -u > "$pathlist.tmp"
mv "$pathlist.tmp" "$pathlist"
tr -s '\n' < "$excludelist" | sort -u > "$excludelist.tmp"
mv "$excludelist.tmp" "$excludelist"
echo " ok"
