#!/bin/sh -eu

. "$(dirname "$(realpath "$0")")/COMMON"

require apk

apk list -I --manifest | awk '{print $1}' | xargs -J {} apk info -s --verbose "{}" | awk '{print $2 $3 " " $1}' | sed 's/\:$//' | sort -h 
