#!/bin/sh -eu

. "$(dirname "$0")/COMMON"

## pipe to it
calculate_length()( python3 -c 'import sys; from wcwidth import wcswidth; print(max(wcswidth(line[:-1]) for line in sys.stdin))' )

## specify $variant
print_banner()
{
	if [ "$(tput cols)" -ge "$( tail +2 "$dir/BANNER_$variant" | calculate_length)" ]
	then tail +2 "$dir/BANNER_$variant"
	else head -1 "$dir/BANNER_$variant"; repeat "$(tput cols)" '─'
	fi
}

get_variant()
{
[ "$in_termux" = 1 ] && variant="TERMUX" && return || :
case "(lsb_release -sc)" in
chimera) variant="CHIMERA";;
alpine) variant="ALPINE";;
esac
variant="DEFAULT"
}

## main
## variant override
[ "${b+x}" ] && variant="$1" || get_variant
print_banner
