#!/bin/sh -eu

. "$(dirname "$0")/COMMON"

require cmd:tput

print_banner() ### ( file )
{
	local banner="$dir/BANNERS/$1"
	[ -f "$banner" ] || return 1
	local singleline=0
	[ "$in_fbcon" = 0 ] || singleline=1
	[ "$COLUMNS" -ge "$(head -1 "$banner")" ] || singleline=1
	if [ "$singleline" = 1 ]
	then tail +2 "$banner" | head -1 ; repeat "$COLUMNS" '─'
	else tail +3 "$banner"
	fi
}

get_variant()
{
variant="$(. "$dir/distinfo" ID)"
}

## main

## variant override
variant="${1-}"
[ "$variant" ] || get_variant

print_banner "$variant" || print_banner DEFAULT
