#!/bin/sh -eu

. "$(dirname "$0")/COMMON"

## pipe to it
calculate_length()( python3 -c 'import sys; from wcwidth import wcswidth; print(max(wcswidth(line[:-1]) for line in sys.stdin))' )

tail +2 "$1" | calculate_length
