#!/bin/sh -eu

. "$(dirname "$(realpath "$0")")/COMMON"

require python-wcwidth

## pipe to it
calculate_length()
{
	python3 -c 'import sys; from wcwidth import wcswidth; print(max(wcswidth(line[:-1]) for line in sys.stdin))'
}

tail +3 "$1" | calculate_length
