#!/bin/bash
## not executable, just for syntax highlighting

[ "${_initialized-}" = 1 ] && error "S already initialized" || :
## start of main

[ "${NO_SETEU-}" = 1 ] || set -eu

script="$(realpath "$0")"
dir="${script%/*}"
prog="${0##*/}"
realprog="{$script##*/}"
errormsg=
errormsg2=

## dynloaded functions
debugsh(){ include misc; debugsh "$@"; }
justdo(){ include misc; justdo "$@"; }
countdown(){ include misc; countdown "$@"; }
head_except(){ include misc; head_except "$@"; }

banner(){ include greet; banner "$@"; }
todo(){ include greet; todo "$@"; }
greet(){ include greet; greet "$@"; }

apksize(){ include pkg; apksize "$@"; }
apk_world_dedup(){ include pkg; apk_world_dedup "$@"; }

hitokoto(){ include net; hitokoto "$@"; }
dynv6_update(){ include net; dynv6_update "$@"; }

## Public Functions
call(){ "$@"; }
error(){ echo "$prog: ${errormsg}$1${errormsg2}" >&2; return "${2-1}"; }
is_empty(){ awk 'NF {exit 1}' "$1"; }
include(){ local i; for i in "$@"; do . "$dir/LIB/$i"; done; }
getshpid(){ require linux; grep PPid: "/proc/$$/status" | awk '{print $2}'; }
repeat(){ awk -v n="$1" -v s="$2" 'BEGIN{++n;while(--n)printf "%s",s}'; }

require()
{
	local i
	local errormsg="error: need "
	local errormsg2=", please check system environment"
	notfound(){ error "${1-"$i"}"; }
	for i in "$@"
	do	case "$1" in
		root) [ "$(id -u)" = 0 ] || errormsg2=" privilege" notfound;;
		android|termux) [ "$in_termux" = 1 ] || notfound "android(termux) environment";;
		non_android|non_termux) [ "$in_termux" = 0 ] || notfound "non-android(linux distro) environment";;
		linux) [ "$on_linux" = 1 ] || notfound "system running on linux kernel";;
		python-*) local modname="${i#python-}"; python -c "import $modname" || notfound "python module $modname";;
		dir:*) [ -d "${i#dir:}" ] || notfound;;
		file:*) [ -f "${i#file:}" ] || notfound;;
		fsentry:*) [ -e "${i#fsentry:}" ] || notfound "file $i";;
		cmd:*) type "${i#cmd:}" >/dev/null 2>&1 || notfound;;
		*) errormsg="unknown requirement: " errormsg2= notfound;;
		esac
	done
}

calculate_sum() ### ( column: 1, [file], ... )
{
	local col="${1-}"; [ "$col" ] || col=1; [ "$#" = 0 ] || shift
	awk '{gsub(/,/, "", $'"$col"'); sum += $'"$col"'} END {print sum}' "$@"
}

distinfo()
{
	[ "$in_termux" = 0 ] || { echo termux; return; }
require file:/etc/os-release || { echo "unknown"; return; }
	grep "^${1-}=\".*\"" /etc/os-release | grep -o '".*[^"]' | tail -c +2
}

[ "${TERMUX_VERSION+x}" ] && in_termux=1 || in_termux=0
case "$(uname -s)" in
Linux|MSYS*) on_linux=1;;
*) on_linux=0;;
esac
[ "$TERM" = "linux" ] && in_fbcon=1 || in_fbcon=0
require cmd:tput
[ "${COLUMNS-}" ] || COLUMNS="$(tput cols)"

## end of main
_initialized=1
