#!/bin/sh -eu

. "$(dirname "$0")/COMMON"

## preload

fifo="$(mktemp -u)"
mkfifo "$fifo"
"$dir/hitokoto" > "$fifo" 2>&1 &

"$dir/banner"
echo "PID: $(getshpid)"
cat "$fifo"; rm -f "$fifo"
"$dir/todo"
cat "$dir/PS"
