#!/bin/sh -eu

. "$(dirname "$(realpath "$0")")/COMMON"

require android cmd:/system/bin/app_process

### remade from sui's rish script

dexfile="$dir/RES/rish_sui.dex"
[ -f "$dexfile" ] || error "dex file not found, please put rish_sui.dex in $dir/RES/"
[ -f "$dir/RES/librish.so" ] || error "lib file not found, please put librish.so in $dir/RES/"

if [ $(getprop ro.build.version.sdk) -ge 34 ]
then	[ ! -w "$dexfile" ] || chmod a-w "$dexfile"
	[ ! -w "$dexfile" ] || error "cannot chmod a-x $dexfile, please fix it yourself"
fi

[ "${RISH_APPLICATION_ID-}" ] || export RISH_APPLICATION_ID="com.termux"
/system/bin/app_process -Djava.class.path="$dexfile" -Dsui.library.path="$dir/RES" /system/bin --nice-name=rish rikka.sui.shell.Shell "$@"
