#!/bin/sh -eu

. "$(dirname "$(realpath "$0")")/COMMON"

require android cmd:/system/bin/app_process

### remade from shizuku's rish script

dexfile="$dir/RES/rish_shizuku.dex"
[ -f "$dexfile" ] || error "dexfile file not found, please put rish_shizuku.dexfile in $dir/RES/"

if [ $(getprop ro.build.version.sdk) -ge 34 ]
then	[ ! -w $dexfile ] || chmod a-w $dexfile
	[ ! -w $dexfile ] || error "cannot chmod a-x $dexfilefile, please locate problem yourself"
fi

[ "${RISH_APPLICATION_ID-}" ] || export RISH_APPLICATION_ID="com.termux"
/system/bin/app_process -Djava.class.path="$dexfile" /system/bin --nice-name=rish rikka.shizuku.shell.ShizukuShellLoader "$@"
