#!/data/data/com.termux/files/usr/bin/bash -eu

. "$(dirname "$0")/COMMON"

world_file="$HOME/.termux/world"
help_exit()
{
cat <<EOF
$prog: termux apt wrapper to imitate apk world
    usage: $prog COMMAND
    command:  apply    set manual/auto state according to world
              save     save current manual package list to world
              help     show this help
EOF
exit "$1"
}

apply_world()
{
apt-mark auto "*" >/dev/null
apt-mark manual $(cat "$world_file") >/dev/null ||
([ "$?" = 100 ] && pkg add $(cat "$world_file"))
}

save_world()
{
apt-mark showmanual > "$world_file"
}

sort_world()
{
export LC_ALL=C
< "$world_file" tr -s '\n' | sort -u > "$world_file.tmp"
mv "$world_file.tmp" "$world_file"

}

[ "$#" = 0 ] && help_exit 0
case $1 in help) help_exit
;; apply) apply_world
;; save) save_world
;; *) help_exit 1
esac
