#!/bin/sh -eu

. "$(dirname "$0")/COMMON"

if [ "$(tput cols)" -ge "$(wc -mL "$dir/BANNER_TERMUX" | awk '{print $2}')" ]
then cat "$dir/BANNER_TERMUX"
else echo 'Welcome to Termux!'; repeat "$COLUMNS" '─'
fi
