#!/bin/env python
# -*- coding: utf-8 -*-
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (c) 2024-2025 BarryLhm<BarryLhm@outlook.com>

"""termux-proot.py"""

import sys
import os

## Static Difinitions
debug_env = "DEBUGGING"
debug_magic = "1"
termux_data = "/data/data/com.termux"
termux_root = termux_data + "/files"
termux_home = termux_root + "/home"
termux_usr = termux_root + "/usr"
termux_bin = termux_usr + "/bin"
storage = ["/storage", "/sdcard", "/mnt"]
android_inaccessible = ["/proc/partitions"]
usrlocal_bin = ["/usr/local/sbin", "/usr/local/bin"]
nullfile = "/dev/null"
debugging = (
    True if debug_env in os.environ and os.environ[debug_env] == debug_magic else False
)


def if_dir(*dirs: str) -> list:
    return [d for d in dirs if os.path.isdir(d)]


def if_file(*files: str) -> list:
    return [f for f in files if os.path.isfile(f)]


path_android = if_dir(
    "/system/bin",
    "/system/xbin",
    "/system_ext/bin",
    "/system_ext/xbin",
    "/vendor/bin",
    "/product/bin",
)
android_runtime = if_dir("/system", "/vendor", "/product", "/apex") + if_file(
    "/linkerconfig/ld.config.txt"
)


def print_help() -> None:
    prog = sys.argv[0]
    print(
        prog
        + ": Termux Proot Helper\n      usage: "
        + prog
        + """ ROOT CMDLINE
"""
    )


def debug(message) -> None:
    if debugging:
        print("\033[2m" + str(message) + "\033[0m\n")


def main(argv: list) -> int:
    if len(argv) < 2:
        print_help()
        exit(1)

    ## defaults
    root = "/"
    id = "0:0"
    wd = "/"
    hardlink_emu = True
    binds = ["/dev", "/proc", "/sys"]
    masks = []
    cmdline = ["/bin/sh"]
    PATH = ["/usr/sbin", "/usr/bin/sbin", "/bin"]
    env = {
        "HOME": "/",
        "LANG": "C",
        "TERM": os.environ["TERM"],
    }

    ## ---
    fix_permission_denied = path_usrlocal = share_android = share_termux = (
        share_storage
    ) = share_tmp = False
    ## conf
    root = argv[1]
    cmdline = argv[2:]
    env["HOME"] = wd = "/root"
    env["LANG"] = "zh_CN.UTF8"
    binds += [termux_bin, termux_home + ":" + env["HOME"]]

    fix_permission_denied = path_usrlocal = share_android = share_termux = (
        share_storage
    ) = share_tmp = True

    ## config
    if fix_permission_denied:
        masks += android_inaccessible
    if share_tmp:
        binds += [termux_usr + "/tmp:/tmp"]
    if share_storage:
        binds += storage
    if share_android:
        binds += android_runtime
    if share_termux:
        binds += [termux_data]
    if path_usrlocal:
        PATH = usrlocal_bin + PATH

    ## final process & execute
    opts = ["-r", root, "-i", id, "-w", wd]
    if hardlink_emu:
        opts += ["-l"]
    binds += [nullfile + ":" + p for p in masks]
    opts += [item for p in binds for item in ["-b", str(p)]]
    env["PATH"] = ":".join(PATH)

    debug(binds)
    debug("execvpe(proot" + str(["proot"] + opts + cmdline) + str(env) + ")")

    os.execvpe("proot", ["proot"] + opts + cmdline, env)


if __name__ == "__main__":
    exit(main(sys.argv))
