#!/bin/sh -eu

. "$(dirname "$0")/COMMON"

require cmd:tput

cat << EOF
╔═════╗
║Todo:╟$(repeat "$(( $COLUMNS - 7 ))" '─')
╚═════╝
$(cat ~/TODO)
$([ ! -f ~/TODO_EXT ] || cat ~/TODO_EXT)
$(repeat "$COLUMNS" '─')
EOF
