[options]
HoldPkg     = pacman glibc
Architecture = auto

#UseSyslog
Color
ILoveCandy
#CheckSpace
VerbosePkgLists
DisableDownloadTimeout
ParallelDownloads = 20
DownloadUser = alpm
#DisableSandbox

#SigLevel    = Required
SigLevel    = Required DatabaseOptional
#SigLevel    = Never
LocalFileSigLevel = Optional

[cachyos-v3]
Include = /etc/pacman.d/mirror.d/cachyos_v3

[cachyos-extra-v3] 
Include = /etc/pacman.d/mirror.d/cachyos_v3

[cachyos-core-v3] 
Include = /etc/pacman.d/mirror.d/cachyos_v3

[cachyos]
Include = /etc/pacman.d/mirror.d/cachyos

[core]
Include = /etc/pacman.d/mirror.d/arch

[extra]
Include = /etc/pacman.d/mirror.d/arch

[archlinuxcn]
Include = /etc/pacman.d/mirror.d/archlinuxcn

[multilib]
Include = /etc/pacman.d/mirror.d/arch

[chaotic-aur]
Server = https://chaoticmirror.com/chaotic-aur/$repo/$arch
#Include = /etc/pacman.d/mirror.d/chaotic-aur
